[project]
authors = ["Lael D. Barlow"]
channels = ["etetoolkit", "conda-forge", "bioconda"]
description = "Workflow for identifying and classifying homologous gene/protein sequences"
name = "amoebae"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
ete3 = ">=3.1.3,<4"
biopython = ">=1.84,<2"
hmmer = ">=3.4,<4"
gffutils = ">=0.13,<0.14"
pypdf2 = ">=3.0.1,<4"
reportlab = ">=4.2.5,<5"
pandoc = ">=3.5,<4"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.7,<3.9"
graphviz = ">=12.0.0,<13"
snakemake = ">=8.25.1,<9"
curl = ">=8.10.1,<9"
certifi = ">=2024.12.14,<2025"
# Note: blast, exonerate, and muscle=3.8 must also be installed (e.g., globally), but are not defined here because installation is system-specific.
