#!/bin/bash

# Record time.
timestamp=$(date +%s)

# Get the path to the script to copy.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT=$DIR'/test_computecanada_environment.sh'

# Copy template script to current working directory.
NEW=$PWD'/amoebae_cc_script_'$timestamp'.sh'
cp $SCRIPT $NEW
echo 'Wrote new script: '$NEW
